In [53]:
import pandas as pd

In [54]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', sep=',')

In [55]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [56]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [57]:
df.drop('PassengerId', axis=1, inplace=True)

In [58]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [59]:
df.drop(3, inplace=True)

In [60]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
df.set_index('Name', inplace=True)

In [62]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
df.reset_index(inplace=True)

In [64]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [65]:
d = {'key1': [4, 3, 5, 6, 3],
     'key2': [1, 2, 3, 4, 5],
     'key3': [2, 3, 4, 5, 6]
     }

In [66]:
pd.DataFrame(d)

   key1  key2  key3
0     4     1     2
1     3     2     3
2     5     3     4
3     6     4     5
4     3     5     6

In [67]:
# Ames Housing dataset (with NaNs) from open repo
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

# Read dataset
df1 = pd.read_csv(url)

In [68]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [69]:
df1.dropna(inplace=True)

In [70]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [71]:
df1.fillna("Shiva", inplace=True)

In [72]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [73]:
df.reset_index(inplace=True)

In [74]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [75]:
g = df.groupby('Survived')

In [76]:
g

In [77]:
g.sum()

,index,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,,,
0,244315,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",1390,malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...
1,151290,"Cumings, Mrs. John Bradley (Florence Briggs Th...",666,femalefemalefemalefemalefemalefemalefemalemale...,8184.67,161,159,PC 17599STON/O2. 3101282347742237736PP 9549113...,16498.1294,C85G6C103D56A6B78D33C52B28F33C23 C25 C27D10 D1...,CSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCSC...

In [78]:
g1 = df.groupby(['Survived', 'Sex'])

In [79]:
g1.sum()

                  index                                               Name  \
Survived Sex
0        female   35061  Vestrom, Miss. Hulda Amanda AdolfinaVander Pla...
         male    209254  Braund, Mr. Owen HarrisAllen, Mr. William Henr...
1        female   99654  Cumings, Mrs. John Bradley (Florence Briggs Th...
         male     51636  Williams, Mr. Charles EugeneBeesley, Mr. Lawre...

                 Pclass       Age  SibSp  Parch  \
Survived Sex
0        female     231   1603.00     98     84
         male      1159  11382.50    206     97
1        female     446   5648.00    119    120
         male       220   2536.67     42     39

                                                            Ticket  \
Survived Sex
0        female  350406345763349909345764754611668349237CA 2144...
         male    A/5 2117137345033087717463349909A/5. 215134708...
1        female  PC 17599STON/O2. 3101282347742237736PP 9549113...
         male    2443732486981137882677199472661160124873834577...

                       Fare  \
Survived Sex
0        female   1864.9752
         male    10277.7447
1        female  12048.5876
         male     4449.5418

                                                             Cabin  \
Survived Sex
0        female                           C49G6G6C22 C26C22 C26E77
         male    E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...
1        female  C85G6C103B78D33B28F33C23 C25 C27E101F E69D47C2...
         male    D56A6C52D10 D12F4F2A31C93D35C106C22 C26F2E50B9...

                                                          Embarked
Survived Sex
0        female  SSSSSSSSSCSCSSCSSCSSSSSCSSSQSSSSSCSSSSSSSSSSSS...
         male    SSQSSSSQSCSSCSCSSCSQCSSCCSCSSCSSSSCSSSSSSSSSSS...
1        female  CSSCSSSCQSQCQCCQQCSSSSSSQSSSSSQSCSSSSSQSSSSQSS...
         male    SSSCSCSSSCSCSSSSSSSCCSSSSSSSSSSSQSSSSCSSSSSSSS...

In [80]:
g2 = df.groupby('Pclass')

In [81]:
g2.sum(numeric_only=True)

         index  Survived      Age  SibSp  Parch        Fare
Pclass
1        99272       135  7076.42     89     77  18124.3125
2        81688        87  5168.83     74     70   3801.8417
3       214645       119  8924.92    302    193   6714.6951

In [82]:
g2.mean(numeric_only=True)

             index  Survived        Age     SibSp     Parch       Fare
Pclass
1       461.730233  0.627907  38.250919  0.413953  0.358140  84.299128
2       443.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3       437.158859  0.242363  25.140620  0.615071  0.393075  13.675550

In [83]:
g2.max(numeric_only=True)

        index  Survived   Age  SibSp  Parch      Fare
Pclass
1         888         1  80.0      3      4  512.3292
2         885         1  70.0      3      3   73.5000
3         889         1  74.0      8      6   69.5500

In [84]:
# Group the DataFrame and calculate the mean for numeric columns
g2 = df.groupby('Pclass')
g2.mean(numeric_only=True)

             index  Survived        Age     SibSp     Parch       Fare
Pclass
1       461.730233  0.627907  38.250919  0.413953  0.358140  84.299128
2       443.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3       437.158859  0.242363  25.140620  0.615071  0.393075  13.675550

In [85]:
for pclass, group_df in g2:
    print(f"Class: {pclass}")
    display(group_df['Name'].head())

Class: 1

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
5                               McCarthy, Mr. Timothy J
10                             Bonnell, Miss. Elizabeth
22                         Sloper, Mr. William Thompson
26                       Fortune, Mr. Charles Alexander
Name: Name, dtype: object

Class: 2

8     Nasser, Mrs. Nicholas (Adele Achem)
14       Hewlett, Mrs. (Mary D Kingcome)
16           Williams, Mr. Charles Eugene
19                   Fynney, Mr. Joseph J
20                  Beesley, Mr. Lawrence
Name: Name, dtype: object

Class: 3

0           Braund, Mr. Owen Harris
2            Heikkinen, Miss. Laina
3          Allen, Mr. William Henry
4                  Moran, Mr. James
6    Palsson, Master. Gosta Leonard
Name: Name, dtype: object

In [86]:
g2.max(numeric_only=True)

        index  Survived   Age  SibSp  Parch      Fare
Pclass
1         888         1  80.0      3      4  512.3292
2         885         1  70.0      3      3   73.5000
3         889         1  74.0      8      6   69.5500

In [87]:
g2.max(numeric_only=True)['Age']

Pclass
1    80.0
2    70.0
3    74.0
Name: Age, dtype: float64

In [88]:
g2.max(numeric_only=True)['Age']

Pclass
1    80.0
2    70.0
3    74.0
Name: Age, dtype: float64

In [89]:
df5 = df[['Name', 'Age']][0:10]

In [90]:
df6 = df[['Name', 'Age']][20:35]

In [91]:
pd.concat([df5, df6])

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3                            Allen, Mr. William Henry  35.0
4                                    Moran, Mr. James   NaN
5                             McCarthy, Mr. Timothy J  54.0
6                      Palsson, Master. Gosta Leonard   2.0
7   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
8                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
9                     Sandstrom, Miss. Marguerite Rut   4.0
20                              Beesley, Mr. Lawrence  34.0
21                        McGowan, Miss. Anna "Annie"  15.0
22                       Sloper, Mr. William Thompson  28.0
23                      Palsson, Miss. Torborg Danira   8.0
24  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0
25                            Emir, Mr. Farred Chehab   NaN
26                     Fortune, Mr. Charles Alexander  19.0
27                      O'Dwyer, Miss. Ellen "Nellie"   NaN
28                                Todoroff, Mr. Lalio   NaN
29                           Uruchurtu, Don. Manuel E  40.0
30     Spencer, Mrs. William Augustus (Marie Eugenie)   NaN
31                           Glynn, Miss. Mary Agatha   NaN
32                              Wheadon, Mr. Edward H  66.0
33                            Meyer, Mr. Edgar Joseph  28.0
34                     Holverson, Mr. Alexander Oskar  42.0

In [92]:
pd.concat([df5, df6], axis=1)

,Name,Age,Name,Age
0,"Braund, Mr. Owen Harris",22.0,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,NaN,NaN
2,"Heikkinen, Miss. Laina",26.0,NaN,NaN
3,"Allen, Mr. William Henry",35.0,NaN,NaN
4,"Moran, Mr. James",NaN,NaN,NaN
5,"McCarthy, Mr. Timothy J",54.0,NaN,NaN
6,"Palsson, Master. Gosta Leonard",2.0,NaN,NaN
7,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,NaN,NaN
8,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,NaN,NaN
9,"Sandstrom, Miss. Marguerite Rut",4.0,NaN,NaN
20,NaN,NaN,"Beesley, Mr. Lawrence",34.0
21,NaN,NaN,"McGowan, Miss. Anna ""Annie""",15.0
22,NaN,NaN,"Sloper, Mr. William Thompson",28.0
23,NaN,NaN,"Palsson, Miss. Torborg Danira",8.0
24,NaN,NaN,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0
25,NaN,NaN,"Emir, Mr. Farred Chehab",NaN
26,NaN,NaN,"Fortune, Mr. Charles Alexander",19.0
27,NaN,NaN,"O'Dwyer, Miss. Ellen ""Nellie""",NaN
28,NaN,NaN,"Todoroff, Mr. Lalio",NaN
29,NaN,NaN,"Uruchurtu, Don. Manuel E",40.0
30,NaN,NaN,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN
31,NaN,NaN,"Glynn, Miss. Mary Agatha",NaN
32,NaN,NaN,"Wheadon, Mr. Edward H",66.0
33,NaN,NaN,"Meyer, Mr. Edgar Joseph",28.0
34,NaN,NaN,"Holverson, Mr. Alexander Oskar",42.0

In [93]:
fill_nan = pd.concat([df5, df6], axis=1)

In [94]:
fill_nan.fillna(0, inplace=True)

In [95]:
fill_nan

,Name,Age,Name,Age
0,"Braund, Mr. Owen Harris",22.0,0,0.0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,0,0.0
2,"Heikkinen, Miss. Laina",26.0,0,0.0
3,"Allen, Mr. William Henry",35.0,0,0.0
4,"Moran, Mr. James",0.0,0,0.0
5,"McCarthy, Mr. Timothy J",54.0,0,0.0
6,"Palsson, Master. Gosta Leonard",2.0,0,0.0
7,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,0.0
8,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,0,0.0
9,"Sandstrom, Miss. Marguerite Rut",4.0,0,0.0
20,0,0.0,"Beesley, Mr. Lawrence",34.0
21,0,0.0,"McGowan, Miss. Anna ""Annie""",15.0
22,0,0.0,"Sloper, Mr. William Thompson",28.0
23,0,0.0,"Palsson, Miss. Torborg Danira",8.0
24,0,0.0,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0
25,0,0.0,"Emir, Mr. Farred Chehab",0.0
26,0,0.0,"Fortune, Mr. Charles Alexander",19.0
27,0,0.0,"O'Dwyer, Miss. Ellen ""Nellie""",0.0
28,0,0.0,"Todoroff, Mr. Lalio",0.0
29,0,0.0,"Uruchurtu, Don. Manuel E",40.0
30,0,0.0,"Spencer, Mrs. William Augustus (Marie Eugenie)",0.0
31,0,0.0,"Glynn, Miss. Mary Agatha",0.0
32,0,0.0,"Wheadon, Mr. Edward H",66.0
33,0,0.0,"Meyer, Mr. Edgar Joseph",28.0
34,0,0.0,"Holverson, Mr. Alexander Oskar",42.0

In [96]:
m1 = {'key1': [4, 3, 5, 6, 3],
     'key2': [1, 2, 3, 4, 5],
     'key3': [2, 3, 4, 5, 6]
     }

In [97]:
m2 = {'key1': [4, 3, 5, 6, 3],
     'key4': [1, 2, 5, 53, 7],
     'key5': [2, 76, 4, 97, 4]
     }

In [98]:
df_m1 = pd.DataFrame(m1)
df_m2 = pd.DataFrame(m2)
pd.merge(df_m1, df_m2)

   key1  key2  key3  key4  key5
0     4     1     2     1     2
1     3     2     3     2    76
2     3     2     3     7     4
3     5     3     4     5     4
4     6     4     5    53    97
5     3     5     6     2    76
6     3     5     6     7     4

In [99]:
pd.merge(df_m1, df_m2, how='outer')

   key1  key2  key3  key4  key5
0     3     2     3     2    76
1     3     2     3     7     4
2     3     5     6     2    76
3     3     5     6     7     4
4     4     1     2     1     2
5     5     3     4     5     4
6     6     4     5    53    97

In [100]:
pd.merge(df_m1, df_m2, how='left')

   key1  key2  key3  key4  key5
0     4     1     2     1     2
1     3     2     3     2    76
2     3     2     3     7     4
3     5     3     4     5     4
4     6     4     5    53    97
5     3     5     6     2    76
6     3     5     6     7     4

In [101]:
pd.merge(df_m1, df_m2, how='right')

   key1  key2  key3  key4  key5
0     4     1     2     1     2
1     3     2     3     2    76
2     3     5     6     2    76
3     5     3     4     5     4
4     6     4     5    53    97
5     3     2     3     7     4
6     3     5     6     7     4

In [102]:
pd.merge(df_m1, df_m2, how='cross')

    key1_x  key2  key3  key1_y  key4  key5
0        4     1     2       4     1     2
1        4     1     2       3     2    76
2        4     1     2       5     5     4
3        4     1     2       6    53    97
4        4     1     2       3     7     4
5        3     2     3       4     1     2
6        3     2     3       3     2    76
7        3     2     3       5     5     4
8        3     2     3       6    53    97
9        3     2     3       3     7     4
10       5     3     4       4     1     2
11       5     3     4       3     2    76
12       5     3     4       5     5     4
13       5     3     4       6    53    97
14       5     3     4       3     7     4
15       6     4     5       4     1     2
16       6     4     5       3     2    76
17       6     4     5       5     5     4
18       6     4     5       6    53    97
19       6     4     5       3     7     4
20       3     5     6       4     1     2
21       3     5     6       3     2    76
22       3     5     6       5     5     4
23       3     5     6       6    53    97
24       3     5     6       3     7     4

In [107]:
m1 = pd.DataFrame({'key1': [4, 3, 5, 6, 3],
     'key2': [1, 2, 3, 4, 5],
     'key3': [2, 3, 4, 5, 6]
}, index=['f', 'g', 'h', 'i', 'j']
)

In [108]:
m2 = pd.DataFrame({'key4': [4, 3, 5, 6, 3],
     'key5': [1, 0, 3, 4, 0],
     'key6': [2, 9, 2, 5, 5]
}, index=['f', 'g', 'h', 'i', 'j']
)

In [105]:
m1

   key1  key2  key3
f     4     1     2
g     3     2     3
h     5     3     4
i     6     4     5
j     3     5     6

In [106]:
m2

   key1  key2  key3
f     4     1     2
g     3     0     9
h     5     3     2
i     6     4     5
j     3     0     5

In [109]:
m1.join(m2)

   key1  key2  key3  key4  key5  key6
f     4     1     2     4     1     2
g     3     2     3     3     0     9
h     5     3     4     5     3     2
i     6     4     5     6     4     5
j     3     5     6     3     0     5

In [112]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [114]:
df['Fare_INR'] = df['Fare'].apply(lambda x : x*80)

In [115]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1040.000
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2400.000
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1876.000
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2400.000
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,620.000

In [116]:
def euro_inr(x):
  return x*80
df['Fare_INR'] = df['Fare'].apply(euro_inr)

In [117]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1040.000
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2400.000
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1876.000
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2400.000
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,620.000

In [118]:
df['name_len'] = df['Name'].apply(len)

In [119]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,name_len
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000,23
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664,51
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000,22
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000,24
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1040.000,21
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2400.000,28
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1876.000,40
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2400.000,21
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,620.000,19

In [121]:
def cat_fare(x):
  if x<10:
    return "cheap"
  elif x>=10 and x<20:
    return "mid"
  else:
    return "high"

In [122]:
df['cat_fare'] = df['Fare'].apply(cat_fare)

In [123]:
df

,index,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,name_len,cat_fare
0,0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000,23,cheap
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664,51,high
2,2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000,22,cheap
3,3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S,644.000,24,cheap
4,4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q,676.664,16,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,1040.000,21,mid
886,886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,2400.000,28,high
887,887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1876.000,40,high
888,888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,2400.000,21,high
889,889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,620.000,19,cheap